version: '3.9'
services:
  rekam-medis-service:
    build: ./rekam-medis-service
    ports:
      - "8001:8001"
    env_file:
      - ./rekam-medis-service/.env
    restart: unless-stopped
    environment:
      - RAWATINAP_URL=http://rawat-inap-service:4000/graphql

  rawat-inap-service:
    build: ./rawat-inap-service
    ports:
      - "4000:4000"
    env_file:
      - ./rawat-inap-service/.env
    restart: unless-stopped
    environment:
      - REKAMMEDIS_URL=http://rekam-medis-service:8001/graphql

  rawat-jalan-service:
      build: ./rawat_jalan_service
      ports:
        - "8004:8004"
      env_file:
        - ./rawat_jalan_service/backend/.env
      restart: unless-stopped
      environment:
        - RAWATINAP_URL=http://rawat-inap-service:4000/graphql

  # data-individu:
  #   build: ./DataIndividu
  #   ports:
  #     - "8002:8002"
  #   env_file:
  #     - ./DataIndividu/.env
  #   restart: unless-stopped